services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: challenge_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d challenge_dev"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    image: challenge:dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: db
      DB_NAME: challenge_dev
      DB_USER: dev
      DB_PASS: dev
    ports:
      - "8080:8080"
