spring:
  docker:
    compose:
      enabled: false
      file: ./docker-compose.dev.yml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:challenge_dev}
    username: ${DB_USER:dev}
    password: ${DB_PASS:dev}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  percentage:
    fail: false
    mock: 50
  cors:
    allowed-origins: "*"
  async:
    thread-name-prefix: "async-"
    core-pool-size: 2
    MaxPoolSize: 4
    QueueCapacity: 1000

server:
  port: 8080